# Generated by Django 3.2.5 on 2023-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='receive_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
