# Generated by Django 3.2.5 on 2023-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20230811_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeitem',
            name='title',
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
