export const styles = {
    mainBox: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        bgcolor: 'background.default',
        pt: '1.5rem',
        pb: '1.5rem',
    },
    secondBox: {
        border: '2px solid',
        borderColor: 'secondary.main',
        display: 'flex',
        flexDirection: 'column',
        width: '80%',
        margin: 'auto',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        borderRadius: '.6rem',
        bgcolor: 'background.white',
    },
    thirdBox: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // gap: '1rem',
        alignSelf: 'flex-start',
        marginBottom: 'auto',
        p: 3,
        width: '100%',
    },
    centerBox: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        // gap: '1rem',
        alignSelf: 'flex-start',
        marginTop: 'auto',
        p: 3,
        width: '100%',
    },
    icon: {
        color:'secondary.main',
      cursor: 'pointer'
    }
}